language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t pumba94/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true pumba94/react-test npm test

after_success:
  - docker build -t pumba94/multi-client ./client
  - docker build -t pumba94/multi-nginx ./nginx
  - docker build -t pumba94/multi-server ./server
  - docker build -t pumba94/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password -stdin
  - docker push pumba94/multi-client
  - docker push pumba94/multi-nginx
  - docker push pumba94/multi-server
  - docker push pumba94/multi-worker
